train_dir   : 'data/graph_data/train'
valid_dir   : 'data/graph_data/valid'
log_dir     : 'logs/comparisons/dnn/dim-comparison/hid1/'
gpu         : '-1'
n_files     : 1600
n_valid     : 200
n_train     : 1400 
lr          : 0.0001
n_iters     : 1
n_epoch     : 2
TEST_every  : 50
hid_dim     : 1
