train_dir   : 'data/graph_data/train'
valid_dir   : 'data/graph_data/valid'
log_dir     : 'logs/comparisons/dnn/iter-comparison/it2/'
gpu         : '-1'
n_files     : 1600
n_valid     : 200
n_train     : 1400 
lr          : 0.00001
n_iters     : 2
n_epoch     : 2
TEST_every  : 50
hid_dim     : 100
