input_dir   : 'data/hitgraphs_big'
log_dir     : 'logs/tensorflow/ENE/lr_0_01/'
n_files     : 1600
n_valid     : 150
n_train     : 1450 
lr          : 0.01
n_iters     : 1
n_epoch     : 2
TEST_every  : 50
