input_dir   : 'data/hitgraphs_big'
log_dir     : 'logs/tensorflow/dnn/ENE2/lr_0_01/'
n_files     : 1600
n_valid     : 150
n_train     : 1450 
lr          : 0.001
n_iters     : 8
n_epoch     : 10
TEST_every  : 200
