train_dir   : 'data/graph_data/train'
valid_dir   : 'data/graph_data/valid'
log_dir     : 'logs/test/'
gpu         : '-1'
n_files     : 1600
n_valid     : 20
n_train     : 1400
lr          : 0.01
n_iters     : 2
n_epoch     : 1
TEST_every  : 200
hid_dim     : 2
n_thread    : 20
