input_dir   : 'data/hitgraphs_big'
log_dir     : 'logs/test/'
n_files     : 1600
n_valid     : 200
n_train     : 1400
lr          : 0.01
n_iters     : 2
n_epoch     : 10
TEST_every  : 200
hid_dim     : 10
