input_dir   : 'data/hitgraphs_big'
log_dir     : 'logs/tensorflow/ENE8/lr_0_1/'
n_files     : 1600
n_valid     : 150
n_train     : 1450 
lr          : 0.1
n_iters     : 8
n_epoch     : 2
TEST_every  : 50
