input_dir   : 'data/hitgraphs_big'
log_dir     : 'logs/comparisons/dnn/hid10/'
n_files     : 1600
n_valid     : 150
n_train     : 1450 
lr          : 0.0001
n_iters     : 2
n_epoch     : 10
TEST_every  : 200
hid_dim     : 10
